config/routes.rb
Rails.application.routes.draw do
  resources :pictures
  get '/image_of_pictures/:id', to: 'pictures#get_image', as: 'image_of_pictures'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/profile', to: 'users#show'
  delete '/unsubscribe', to: 'users#destroy'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
    belongs_to :user, optional: true
    belongs_to :room, optional: true
    after_create_commit { ChatBroadcastJob.perform_later self }
end

app/models/picture.rb
class Picture < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :user_rooms
    has_many :chats
    has_many :users, through: :user_rooms
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_rooms
  has_many :chats
  has_many :chats, through: :user_rooms

  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true
  validates :email, length: { maximum: 255 }
  validates :email, format: { with: VALID_EMAIL_REGEX }
  validates :email, uniqueness: { case_sensitive: false }

  validates :password, presence: true
  validates :password, length: { minimum: 8 }
  has_secure_password

  validates :name, presence: true
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
    belongs_to :user, optional: true
    belongs_to :room, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
    before_action :set_current_url
    before_action :require_login

    private

    def set_current_url
        session[:current_url] = request.url
    end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
      def show
        # どのユーザーとチャットするかを取得。
        @user = User.find(params[:id])
  
        # カレントユーザーのuser_roomにあるroom_idの値の配列をroomsに代入。
        rooms = current_user.user_rooms.pluck(:room_id)
  
        # user_roomモデルから
        # user_idがチャット相手のidが一致するものと、
        # room_idが上記roomsのどれかに一致するレコードを
        # user_roomsに代入。
        user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)
  
        # もしuser_roomが空でないなら
        unless user_rooms.nil?
          # @roomに上記user_roomのroomを代入
          @room = user_rooms.room
        else
          # それ以外は新しくroomを作り、
          @room = Room.new
          @room.save
          # user_roomをカレントユーザー分とチャット相手分を作る
          UserRoom.create(user_id: current_user.id, room_id: @room.id)
          UserRoom.create(user_id: @user.id, room_id: @room.id)
        end
        @chats = @room.chats
        @chat = Chat.new(room_id: @room.id)
      end
      
      def create
        @chat = current_user.chats.new(chat_params)
        @chat.save
        redirect_to request.referer
      end
    
      private
      def chat_params
        params.require(:chat).permit(:message, :room_id)
      end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  skip_before_action :set_current_url, only: [:get_image]
  before_action :set_picture, only: %i[ show edit update destroy ]

  # GET /pictures or /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1 or /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures or /pictures.json
  def create
    #
    @picture = Picture.new(picture_attributes)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to picture_url(@picture), notice: "Picture was successfully created." }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1 or /pictures/1.json
  def update
    respond_to do |format|
      #
      if @picture.update(picture_attributes)
        format.html { redirect_to picture_url(@picture), notice: "Picture was successfully updated." }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1 or /pictures/1.json
  def destroy
    @picture.destroy

    respond_to do |format|
      format.html { redirect_to pictures_url, notice: "Picture was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  #
  def get_image
    picture = Picture.find(params[:id])
    send_data(picture.image, disposition: :inline)
  end
 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def picture_params
      params.require(:picture).permit(:name, :image)
    end

    def picture_attributes
      {
        name: picture_params[:name], image: picture_params[:image].read
      }
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :set_current_url
    before_action :require_login, only: [:destroy]

    def new
    end
  
    def create
      user = User.find_by(email: params[:email].downcase)
      if user && user.authenticate(params[:password])
        log_in(user)
        #redirect_to profile_path
        redirect_to session[:current_url] ||= profile_path
      else
        flash.now[:danger] = 'メールアドレスかパスワードが間違っています。'
        render 'new'
      end
    end
  
    def destroy
      log_out
      # redirect_to login_path
      redirect_to session[:current_url] ||= login_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:index, :show, :destroy]

      def index
        @users = User.all

        # UserRoomsテーブルからログインユーザーが登録されているレコードを抽出する
			  @currentUserRooms = UserRoom.where(user_id: current_user.id)

          #Entry内のuser_idがMYPAGEのparams.idと同じEntry
		    @userEntry = Entry.where(user_id: @user.id)
		    	#@user.idとcurrent_user.idが同じでなければ
			    unless @user.id == current_user.id
			      @currentUserEntry.each do |cu|
			        @userEntry.each do |u|
			          #もしcurrent_user側のルームidと＠user側のルームidが同じであれば存在するルームに飛ぶ
			          if cu.room_id == u.room_id then
			            @isRoom = true
			            @roomId = cu.room_id
			          end
			        end
			      end
			      #ルームが存在していなければルームとエントリーを作成する
			      unless @isRoom
			        @room = Room.new
			        @entry = Entry.new
			      end
			    end
	  	end

      end

      def new
        @user = User.new
      end
    
      def create
        @user = User.new(user_params)
        if @user.save
          log_in(@user)
          redirect_to profile_path
        else
          render 'new'
        end
      end
    
      def show
        @user = User.find(current_user.id)
      end
    
      def destroy
        current_user.destroy
        redirect_to signup_path
      end
    
      private
        def user_params
          params.require(:user).permit(:name, :email, :password, :password_confirmation)
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
      def log_in(user)
        session[:user_id] = user.id
      end
    
      def current_user
        if session[:user_id]
          @current_user ||= User.find_by(id: session[:user_id])
        end
      end
    
      def logged_in?
        !current_user.nil?
      end
    
      def require_login
        redirect_to login_path if !logged_in?
      end
    
      def log_out
        session.delete(:user_id)
        @current_user = nil
      end
end

app/helpers/user_rooms_helper.rb
module UserRoomsHelper
  def open_room_record(user)
    @currentUserRooms = UserRoom.where(user_id: current_user.id)
    @currentUserRooms.each do |user_room|
        record = UserRoom.where(user_id: user.id, room_id: user_room.room_id)
        if record.nil?
            
    end
    return nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/show.html.erb
<%= form_with model: @chat do |f| %>
    <%= f.text_field :message %>
    <%= f.hidden_field :room_id %>
    <%= f.submit %>
<% end %>
<table>
    <thead>
        <tr>
            <td>投稿者名</td>
            <td>投稿内容</td>
        </tr>
    </thead>
    <tbody>
        <% @chats.each do |chat| %>
            <tr>
                <td><%= chat.user.name %></td>
                <td><%= chat.message %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="alert alert-primary" role="alert">
    A Simple primary alert-check it out!
    </div>

<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

    <%= yield %>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
        <% picture.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%# %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pictures</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.name %></td>
        #
        <td><%= image_tag(url_for(image_of_pictures_path(picture)), size: '100x100', class: 'rounded-circle') %></td>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @picture.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(url_for(image_of_pictures_path(@picture)), size: '100x100') %></td>

</p>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>

app/views/users/new.html.erb
<h1>利用者登録</h1>

<%= form_with model: @user, url: signup_path, local: true do |form| %>
  <% if @user.errors.any? %>
    <strong><%= @user.errors.count %>個のエラーがあります。</strong>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= form.label :email, 'メールアドレス' %>
  <%= form.email_field :email %>

  <%= form.label :password, 'パスワード' %>
  <%= form.password_field :password %>

  <%= form.label :password_confirmation, 'パスワード(確認)' %>
  <%= form.password_field :password_confirmation %>

  <%= form.label :email, '名前' %>
  <%= form.text_field :name %>

  <%= form.submit '登録' %>
<% end %>

app/views/users/show.html.erb
<h1>利用者情報</h1>

<p>メールアドレス：<%= current_user.email %></p>
<p><%= link_to 'ログアウト', logout_path, method: :delete %></p>
<p><%= link_to '登録解除', unsubscribe_path, method: :delete, data: { confirm: '本当に登録解除しますか？' } %></p>


<%# if current_user != @user %>
  <%= link_to 'chatを始める', chat_path(current_user)%>
<%# end %>